version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: symfony-app-php
    volumes:
      - ./app:/var/www/html
      - ./front:/var/www/html/front
    networks:
      - symfony-network

  nginx:
    image: nginx:latest
    container_name: symfony-app-nginx
    volumes:
      - ./app:/var/www/html
      - ./front:/var/www/html/front
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
